package service;



//Generated by MyEclipse

public interface ILunettesService {
	
	public String example(String message);
	public String[][] selectLunettes();
	public String SaveCMD1(int codeCmd, String client, int codeL, int qteCmd);
	
}