package service;

import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import org.hibernate.Session;
import org.hibernate.Transaction;

import DAO.TousCommandes;
import DAO.TousCommandesDAO;

import DAO.LunettesPrix;
import DAO.LunettesPrixDAO;
//Generated by MyEclipse

public class LunettesServiceImpl implements ILunettesService {
	
	public String example(String message) {
		return message;
	}
	
	public String[][] selectLunettes(){
		
		// On instancie la classe LunettesPrixDAO afin de pouvoir untiliser 
		// les Methodes de communication avec la table Lunettes_prix 
		// dans la base de données
		
		LunettesPrixDAO dao = new LunettesPrixDAO();
		
		// On crée une Session hibernate
		
		Session ss = dao.getSession();
		
		// On va recupperer les enregistrement qui existe dans notre 
		// base de données 
		
		
		List<LunettesPrix> result = dao.findAll();
		
		Iterator it = result.iterator();
		
		String table[][] = new String[result.size()][4];
		
		int i=0,j=0;
		
		while(it.hasNext()){
			
			LunettesPrix lp = (LunettesPrix) it.next();
			table[i][0] = lp.getNomL();
			table[i][1] = lp.getDescL();
			table[i][2] = lp.getCodeL().toString();
			table[i][3] = lp.getPrixL().toString();
			i++;
		}
		
		return table;
	}
	
	public String SaveCMD1(int codeCmd, String client, int codeL, int qteCmd){
		
		TousCommandesDAO dao = new TousCommandesDAO();		
		Session ss = dao.getSession();		
		Transaction tr2 = ss.beginTransaction();
		
		TousCommandes touscmd =new TousCommandes();	
		
		touscmd.setClient(client);
		touscmd.setCodeCmd(codeCmd);
		touscmd.setCodeL(codeL);
		touscmd.setDateCmd(new Date());
		touscmd.setQteCmd(qteCmd);
		ss.save(touscmd);		
		tr2.commit();
		
		return "commande enregistrer";
	}
	
}